# Generated by Django 5.0.2 on 2024-02-29 15:26

import apps.collections.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Повод",
                "verbose_name_plural": "Поводы",
            },
        ),
        migrations.CreateModel(
            name="Collect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название"),
                ),
                (
                    "description",
                    models.TextField(max_length=1000, verbose_name="Описание"),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Сумма"
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        upload_to="collect/covers/",
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "ending",
                    models.DateTimeField(
                        validators=[
                            apps.collections.validators.validate_future_datetime
                        ],
                        verbose_name="Окончание",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сбор",
                "verbose_name_plural": "Сборы",
                "default_related_name": "collections",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("amount", models.PositiveIntegerField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "collect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collections.collect",
                        verbose_name="Сбор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж",
                "verbose_name_plural": "Платежи",
                "default_related_name": "payments",
            },
        ),
        migrations.AddField(
            model_name="collect",
            name="contributors",
            field=models.ManyToManyField(
                blank=True,
                related_name="collect_contributors",
                through="collections.Payment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collect",
            name="reason",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="collections.reason",
                verbose_name="Повод",
            ),
        ),
        migrations.AddConstraint(
            model_name="collect",
            constraint=models.UniqueConstraint(
                fields=("author", "reason", "ending"),
                name="collections_collect_unique_author_collections",
            ),
        ),
    ]
