# Generated by Django 5.0.2 on 2024-03-03 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(
                help_text="Введите сумму платежа. Сумма платежа должна быть не меньше 1.",
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=1,
                        message="Сумма платежа должна быть не меньше 1.",
                    )
                ],
            ),
        ),
    ]
