MAX_LENGTH_COLLECT_NAME = 100
MAX_LENGTH_COLLECT_DESCRIPTION = 1000
MAX_LENGTH_REASON_NAME = 100
UPLOAD_PATH_COLLECT_COVER = "collect/covers/"
MIN_VALUE_PAYMENT_AMOUNT = 1
ERROR_TEXT_MIN_VALUE_PAYMENT_AMOUNT = (
    f"Сумма платежа должна быть не меньше {MIN_VALUE_PAYMENT_AMOUNT}."
)
HELP_TEXT_MIN_VALUE_PAYMENT_AMOUNT = (
    f"Введите сумму платежа. {ERROR_TEXT_MIN_VALUE_PAYMENT_AMOUNT}"
)
