name: Code che—Åks

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache Poetry
      uses: actions/cache@v2
      with:
        path: ${{ env.HOME }}/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.0

    - name: Install Poetry
      uses: snok/install-poetry@v1.3.4
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Configure poetry
      run: poetry config virtualenvs.in-project true

    - name: Install dependencies
      run: poetry install
      if: steps.cache-poetry.outputs.cache-hit != 'true'

    - name: Run black
      run: |
        poetry run black --check src/backend/

    - name: Run isort
      run: |
        poetry run isort -c src/backend/

    - name: Run mypy
      run: |
        poetry run mypy src/backend/
